slug: :mikutter_calendar
depends:
  mikutter: 3.0.0
  plugin:
  - gtk
  - gui
  - settings
version: '0.2'
author: Akkiesoft
name: mikutter_calendar
description: カレンダーとスケジュール(Google Calendar)を表示するプラグイン
